--
-- PostgreSQL database dump
--

\restrict P1SIPTxrxaihPRQH0F7hz2shSAP5sGSb7VChFke9VhLfIme3q5gsZ8e7Bxd91Uh

-- Dumped from database version 14.19 (Ubuntu 14.19-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.19 (Ubuntu 14.19-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: booking; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.booking (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    end_date date,
    guest_id character varying(255),
    guests integer,
    start_date date,
    status character varying(255),
    property_id bigint,
    CONSTRAINT booking_status_check CHECK (((status)::text = ANY ((ARRAY['BOOKED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.booking OWNER TO admin;

--
-- Name: booking_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: properties; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.properties (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(2000),
    host_id character varying(255),
    image_url character varying(255),
    location character varying(255),
    max_guests integer,
    price_per_night bigint,
    title character varying(255)
);


ALTER TABLE public.properties OWNER TO admin;

--
-- Name: properties_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.properties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.properties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: booking; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.booking (id, created_at, end_date, guest_id, guests, start_date, status, property_id) FROM stdin;
1	\N	2025-10-04	d9c8d166-00f3-4ed0-a13b-80865c24d123	2	2025-10-01	BOOKED	1
2	\N	2025-10-05	05e1cb4f-6584-4fc3-9732-7cc96906088e	2	2025-10-05	CANCELLED	1
3	\N	2025-10-04	7c80c0e3-04f9-4e33-9f89-8cc36eb0db23	2	2025-10-01	CANCELLED	2
\.


--
-- Data for Name: properties; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.properties (id, created_at, description, host_id, image_url, location, max_guests, price_per_night, title) FROM stdin;
1	2025-09-30 12:31:18.838014	Modern apartment in city center	44eec848-cb34-4930-b0ea-ea7c4e292307	https://example.com/images/city-apartment.jpg	Hyderabad	5	7500	Village Apartment
2	2025-09-30 15:25:42.440974	Avengers Tower	e318cc4b-2357-441d-aec7-9a2bf8ad6a76	https://example.com/images/city-apartment.jpg	NewYork	10	450	Avengers Tower
\.


--
-- Name: booking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.booking_id_seq', 3, true);


--
-- Name: properties_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.properties_id_seq', 2, true);


--
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (id);


--
-- Name: properties properties_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT properties_pkey PRIMARY KEY (id);


--
-- Name: booking fkk3950nylmb7eq009fgw7k6eym; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkk3950nylmb7eq009fgw7k6eym FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- PostgreSQL database dump complete
--

\unrestrict P1SIPTxrxaihPRQH0F7hz2shSAP5sGSb7VChFke9VhLfIme3q5gsZ8e7Bxd91Uh

